apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170292814
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170292814
    app.kubernetes.io/part-of: test-app-170292814
  name: java-quarkus-170292814
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170292814
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170292814
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/user1-tenant/test-app-170292814/java-quarkus-170292814@sha256:2d02f1d3fdd812f037fc0710c5877306128d1aa64d4f6c87dd31334fbc14e3ad
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
